version: '3'

services:
  db:
    image: postgres:11.1
  app:
    build: .
    environment:
      - PGHOST=db
      - MIX_ENV=test
    volumes:
      - .:/opt/app
    depends_on:
      - db
    links:
      - db